services:
  php:
    container_name: slimchat_php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
    user: "${UID}"

volumes:
  mysql-data:
